server:
  port: 7002
springdoc:
  swagger-ui:
    enabled: true
    operations-sorter: method
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/websocket
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
token:
  secret-key: "SECRET"
  refresh-secret-key: "REFRESH_SECRET"
  token-time: 30000
  refresh-token-time: 3000000
  
